---
# Prerequestise  - NGINX server
- name: NGINX /  Export environment variables for NGINX
  become: true
  ansible.builtin.template:
    src: templates/nginx.sh.j2
    dest: /etc/profile.d/nginx.sh
    mode: 0644
  tags: nginx
- name: NGINX /  Add epel-release repository
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
  tags: nginx
- name: NGINX /  Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  tags: nginx
  notify: Enable-nginx
- name: NGINX /  Insert Default Config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf
    dest: "{{ nginx_home }}/nginx.conf"
    mode: 0644
  tags: nginx
  notify: Reload-nginx
# main tasks file for LIGHTHOUSE role
- name: Set facts for NGINX vars
  ansible.builtin.set_fact:
    lighthouse_home: "{{ default_web_root }}/{{ virtual_domain }}"
  tags: lighthouse
- name: Upload .tar.gz file containing binaries from local storage
  become: true
  ansible.builtin.copy:
    src: "./files/lighthouse-master.tar.gz"
    dest: "/tmp/lighthouse-master.tar.gz"
    mode: 0644
  register: download_lighthouse_binaries
  until: download_lighthouse_binaries is succeeded
  tags: lighthouse
- name: Extract lighthouse in the installation directory
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/lighthouse-master.tar.gz"
    dest: "{{ default_web_root }}"
    mode: 0644
  tags: lighthouse
- name: Add virtual domain in NGINX
  become: true
  ansible.builtin.template:
    src: templates/{{ virtual_domain }}.conf
    dest: "{{ nginx_home }}/conf.d/{{ virtual_domain }}.conf"
    mode: 0644
  tags: lighthouse
  notify: Reload-nginx
- name: Change file ownership, group and permissions for NGINX Directory
  become: true
  ansible.builtin.file:
    path: /usr/share/nginx
    owner: nginx
    group: nginx
    mode: 0755
  tags: lighthouse
  notify: Reload-nginx
- name: Ensure installation dir exists
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ lighthouse_home }}"
    mode: 0755
  tags: lighthouse
- name: Export environment variables
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.sh.j2
    dest: /etc/profile.d/lighthouse.sh
    mode: 0644
  tags: lighthouse
